# 示例配置文件 - 可以放在 conf/production/app.yaml
server:
  host: "0.0.0.0"
  port: 8080

database:
  host: "localhost"
  port: 3306
  username: "myapp"
  password: "${DB_PASSWORD}"  # 支持环境变量替换
  name: "production_db"

# 应用配置
debug: false
timeout: 30
log_level: "info"
max_conns: 100

# 标签配置
tags:
  - "production"
  - "web"
  - "api" 